language: python
python:
  # - "3.6"
  - "3.7-dev"

  # command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov

# command to run tests
script:
  - pytest
  - pytest --cov=./

after_success:
  - codecov
